### ISSUE TITLE
Tapping on the search box and dismissing search dialog is slow

### ISSUE THREAD

**Issue by mronkko** [mronkko/ZotPad#101]

**Comment by mronkko** [comment]
This should be easy to fix by running the code in Instruments and checking where the bottleneck is

**Comment by phedlund** [comment]
How to reproduce?

One problem I have a solution for is that the item list currently is not reset (restored) if a search has been performed and later the Done button is tapped with an empty search bar.

**Comment by mronkko** [comment]
This seems to have been fixed. Closing

Created a new issue for the done button #108
