### ISSUE TITLE
import from safari

### ISSUE THREAD

**Issue by elaliberte** [mronkko/ZotPad#24]
Thanks for the great app. Excellent as a read-only app. However, I use my iPad on the go and would love to be able to add citations + PDFs directly from Safari on the iPad. This would be a really useful feature.

**Comment by mronkko** [comment]
This will not be implemented. There are three main reasons:

1) The purpose of this feature is to create new items on the Zotero server. A much more straightforward approach to do this would be to port the existing safari connector (https://github.com/zotero/zotero-connectors) as a bookmarklet. There is some discussion about this in the Zotero forums (http://forums.zotero.org/discussion/16020/bookmarklet-for-zotero-standalone/)

2) The Zotero translators are implemented in javascript. iOS does not support javascript outside Safari (or webkit, to be exact), so all translators would need to be rewritten. 

3) Implementing this in ZotPad would mean that the user would be switching between Safari and ZotPad when adding citations. This would result in poor user experience when compared to bookmarklet.

**Comment by elaliberte** [comment]
Thanks for your response. As a non-programmer, I do not really understsand the details. My comment was about the fact that I have not found a way to add items to my zotero library from my iPad. Basically, I would like to be able to add zotero items (including PDFs) using my iPad, whatever the way (but preferably via zotpad, a bit like what the Papers app does). Than you.

**Comment by mronkko** [comment]
Can you provide a link to a description of this functionality in Papers? This would be useful if/when this is implemented as a bookmarklet. I can then pass it on to Zotero developers.

**Comment by elaliberte** [comment]
Thanks. See the "Import" and "Search" features here:
http://www.mekentosj.com/papers/ipad

**Comment by mronkko** [comment]
That page says that the safari integration is implemented as a bookmarklet, but it seems use the Papers iPad app. I think that this is because papers (as far as I know), does not have a cloud backend, like Zotero. With Zotero the implementation would be similar, but the target of the bookmarlet would be Zotero server. 

A bookmarklet seems to be currently under active development by the Zotero team
https://github.com/zotero/zotero-connectors/tree/master/bookmarklet
