### ISSUE TITLE
crashes when trying to access item offline

### ISSUE THREAD

**Issue by elaliberte** [mronkko/ZotPad#25]
When I'm offline and try to access a zotero item from zotpad (e.g. to read a PDF I've previously downloaded in zotpad when I was online), zotpad crashes. When I'm online, it doesn't.

**Comment by mronkko** [comment]
Thank you for reporting this issue. I need a clarification does "offline" mean that:
1) You have airplane mode on, or disabled WiFi in some other way
2) You have switched ZotPad to offline mode in the preferences
3) Something else

**Comment by elaliberte** [comment]
Thanks.
1) Airplane mode is off, but wifi is off (simply because out of range of a network)
2) Zotpad is set to online mode in settings
3) nothing else I believe

-----Original Message-----

**Comment by elaliberte** [comment]
Update: when switching zotpad to 'offline' mode, while being offline (no wifi), it doesn't crash anymore. Still, would be nice not to have to change this manually in settings when you lose your wifi network and still want to read a PDF that was downloaded before.

-----Original Message-----
From: Etienne Laliberté [mailto:etiennelaliberte@gmail.com] 
Sent: Wednesday, 11 April 2012 1:50 PM
To: 'mronkko'
Subject: RE: [ZotPad] crashes when trying to access item offline (#25)

Thanks.
1) Airplane mode is off, but wifi is off (simply because out of range of a network)
2) Zotpad is set to online mode in settings
3) nothing else I believe

-----Original Message-----

**Comment by mronkko** [comment]
This certainly needs to be fixed. I will look into this later today and if I can track it down, I will publish a fix as 1.0.2 update.

**Comment by mronkko** [comment]
This has been fixed in 1.0.2

**Comment by elaliberte** [comment]
Thanks!
