### ISSUE TITLE
abstract is clipped

### ISSUE THREAD

**Issue by mronkko** [mronkko/ZotPad#37]

**Comment by philip-iii** [comment]
Just a brief follow-up: I discovered there are two types of abstract clipping:
- Last line is halfway clipped - the upper 1/4 of the last line is visible. This is displayed properly after selecting another item and then going back to the item that had the issue, though when going back to the items list in the collection view and selecting the same item, the abstract is clipped again in the same way at the same place.
- Last line is completely clipped - the last line is not displayed at all. It seems it is always the last line only, and selecting another item and then the same one again does not help.

No idea if the two are connected, it may be the same underlying problem causing this or it may be that there are two different issues.

**Comment by mronkko** [comment]
It is clipped because the bounds of the text area that shows the abstract are calculated incorrectly. This should not be difficult to fix.

**Comment by mronkko** [comment]
This turned out to be a much more difficult issue to fix.

It is most likely a bug in Apple's code.

http://stackoverflow.com/questions/3562023/uitextview-partially-rendering-a-line-of-text

I changed the abstract from UITextView to UILabel to fix this.
