### ISSUE TITLE
Add option to sort items by date added

### ISSUE THREAD

**Issue by simonster** [mronkko/ZotPad#43]
Date modified mostly suffices, but date added would be better

**Comment by mronkko** [comment]
Implemented.

**Comment by philip-iii** [comment]
This does not seem to work with the latest beta (18). When using the other sorting options, items are just sorted, but when I select DateAdded, the list of items is completely refreshed and all items show instead "Loading from Zotero server" with progress indicators that seem to never complete. Worse yet, when DateAdded is selected as the sorting field, selecting a different collection also never loads showing the same progress indicators. Maybe it has something to do with using WebDAV, but I'd say this should be looked into (I do not have permission to reopen this issue). The log does not indicate anything unusual.

On a side note "DateAdded" should be "Date Added", but that's just nitpicking ;-).

**Comment by mronkko** [comment]
Reopened. The label is now fixed.

**Comment by mronkko** [comment]
Sorting is now possible with date added. This was only partially implemented earlier.
