### ISSUE TITLE
Preview "not supported" for text/html

### ISSUE THREAD

**Issue by philip-iii** [mronkko/ZotPad#46]
This is a rather minor issue, which however may be a bit misleading to a user. Website snapshot attachments which are frequently automatically saved in Zotero (e.g. from ACM, etc.) are automatically downloaded as well and can in fact be displayed using the integrated preview (as well as opened in other applications. albeit not in Safari). Thus, the notice that "Preview is not supported for text/html" is superfluous and misleading. Unless I am missing a scenario in which preview is really not supported for such attachments, It should be trivial to remove.

**Comment by mronkko** [comment]
ZotPad renders thumbnails of PDFs, but not any other file type. That text was meant to say that, but I agree that it can be misleading. Thanks for reporting, this will be fixed in the next build.

**Comment by mronkko** [comment]
Removed the confusing text
