### ISSUE TITLE
Minor UI glitches with attachments in Beta 18

### ISSUE THREAD

**Issue by philip-iii** [mronkko/ZotPad#54]
I've just tried out the latest beta and I noticed two minor UI glitches (which can probably also be filed as separate issues). 

First one is associated with the item detail view - if there are multiple attachments, when the item is opened, the attachment previews are all stacked to the right (see Exhibit 1 below) and the first one is displayed in the center only after interacting with the attachment preview (if there is only one attachment it is shown in the middle as it used to be for multiple attachments as well). Now there might be a reason that this is by design, but I am more inclined to think that it is a bug.

![Exhibit 1](http://dl.dropbox.com/u/26354242/photo%283%29.PNG)

As a side note, it would be really nice to remember which attachment was in focus for a particular item, but that would probably require more effort that is worth (although, wasn't this how it worked at some point or am I just imagining it was?)

The second issue I ran into has to do with the quick preview display of attachments. When multiple attachments have been opened during a session, there were (and technically still are) two ways to switch between opened attachments in the preview - swiping left and right, and using the left and right arrow buttons in the top bar where the title is. Currently, however, when an attachment is opened the left and right arrow buttons are not displayed at all (although it is still possible to switch between attachments by swiping left and right), and when one switches between attachments, for some reason these buttons are displayed in a weird way - darker and with no arrows on them (see Exhibit 2). Now these can either be removed altogether (which may not be possible) or rather retained in favor of making the switching between attachments functionality more obvious, but displayed correctly (as they used to be).

![Exhibit 2](http://dl.dropbox.com/u/26354242/photo%284%29.PNG)

**Comment by mronkko** [comment]
Does issue 1 happen always, or just sometimes?

Issue 2 is more tricky. The preview uses a built-in quicklook controller that is not meant to be modified. However, it is technically possible to modify the controller buttons. The top right button has been replaced with a custom version to track when a user sends a document to another application. For some reason this caused the arrows to not render. 

I have solved this by removing the arrows for now and will look at how to get them render properly in the 1.2 release, where I need to add more buttons to the top bar to support notes and tagging of attachments.

**Comment by philip-iii** [comment]
OK, thanks for the clarification regarding issue 2. Regarding issue 1, it happens always so far - I've tried about 50 items in different collections with different number of attachments, one thing I did just notice, however, is that it does not happen in landscape mode when selecting items within the same collection - that is, it does happen when you transition from the collection view to the item view, but once on the item view where the other items in the collection are displayed in the left sidebar, selecting different items (or the same item), it does show attachments properly (in the middle). In portrait mode, there is no such sidebar and there is always a transition from the collection view to the item view, thus the issue manifests itself all the time. Maybe this provides a clue where the issue is located.

**Comment by mronkko** [comment]
Issue 1 should be now fixed.

**Comment by philip-iii** [comment]
"I have solved this by removing the arrows for now"

I know it is a minor issue, but the dark buttons still appear once one switches between previously opened attachments by swiping back and forth in the quick preview.

A possible related issue is swiping between attachments in the carousel view refusing to work - it happened once, but I have not been able to replicate it afterwards. One could still select different attachments by tapping on them but swipe stopped working for all items.

**Comment by mronkko** [comment]
Yes, it seems to be the case. Also the action button is returned to the original version without the email option if you go back by swiping.

**Comment by mronkko** [comment]
I have decided to fix this by disabling swiping in the item viewer. The reason is a bit technical: To implement file uploads, ZotPad needs to track which files it sends out, but this cannot be done with the default QuickLook viewer. There are two ways to implement this tracking

1) Replace the action button of the QuickLook viewer with a custom button (this is the current implementation)
2) Use a lower level UIDocumentInteractionController framework

The problem with 1 is that swiping reverts back to the original button, and 2 does not support swiping at all, but this and the animations that swiping triggers would need to be programmed separately. 

Quickly switching between recently viewed files will be implemented in some version after 1.1, at latest when a real PDF reader is included.

**Comment by philip-iii** [comment]
Thanks for the clarifications! Although, I found switching back and forth a useful feature, I can see how the actions feature is more important at the moment and I can deal without the switching feature for the time being.
