### ISSUE TITLE
Crashes when opening attachments 

### ISSUE THREAD

**Issue by philip-iii** [mronkko/ZotPad#55]
I just installed the latest beta (19) and unfortunately it crashes with some PDF attachments (I synchronize attachments over WebDAV). This has not happened with previous builds. I can't really tell what causes it, but it is consistently happening for selected attachments, while others open fine. The log does not provide any further details. Attachments that do open successfully, do so immediately, while attachments that cause a crash seem to take about a second or two to crash the app. In some cases where there are multiple attachments, some cause consistent crashes while others work fine. One thing that appears to be common for most crashing attachments is that they are named "IEEE Xplore Full Text PDF" (automated name assigned by Zotero when attachments are downloaded from IEEE Xplore). Other attachments having a similar name, i.e.  "ACM Full Text PDF" or also even "IEEE Xplore PDF" (possibly saved with a newer version of Zotero) and even some also named "IEEE Xplore Full Text PDF" do not seem to cause crashes most of the time.

Another possibly related cause for crashes - some attachments show up with a lock icon in the corner and grayed out (or simly just gray sometimes) in the collection view. Selecting such an item always causes ZotPad to crash.

Overall I managed to crash ZotPad about 50 times in the past 15-20 minutes, more than I've ever managed to crash it so far. I hope the crash reporting has not been flooded ;-)

**Comment by mronkko** [comment]
The crash report system is quite scalable, so no problems. In general, it is not necessary to report crashes. The reports tell what I need to know to fix it almost always. If this is not the case, then I will ask for more information. 

Thanks for testing, I will look into the causes of these crashes.

**Comment by mronkko** [comment]
Can you send me one of these files that cause a crash? 

Also, two questions: 
Do the attachment covers render correctly, or do you just see a PDF icon instead when you are in the main user interface? 
Do you open the attachments from the item list, or the item details view?

**Comment by mronkko** [comment]
No need for further info. I can reproduce this with one of my own attachments.

**Comment by mronkko** [comment]
This crash occurs if you open the second item in the attachment carousel, and it is causes by the indexing of views in the carousel conflicting with their internal indexing. I will make a new build that addresses this issue.

**Comment by mronkko** [comment]
Fixed
