### ISSUE TITLE
Support for Starring / Favorites

### ISSUE THREAD

**Issue by philip-iii** [mronkko/ZotPad#87]
There are already issues for Notes (#26) and Tags (#27), both of which may require a considerable amount of effort to implement and thus take a while to be included in releases. In addition support for editing collections would be great but would probably require as much (if not more) effort to implement. What I would like to propose, therefore, is a somewhat simpler mechanism to highlight items of interest and store them in a dedicated collection (or assign a dedicated tag) so that these items are easy to get back to (e.g. ZotPad Favorites / ZotPad Starred). 

An example use case would be browsing through a somewhat large collection (e.g. a preliminary selection of articles from a conference or a journal), skimming through abstracts and PDFs and marking articles of particular interest with the proposed starring / add to favorites functionality while skimming so that one can get back to the selected articles browsing through the whole collection, to look at them in more detail or read them at a later point. Currently, to achieve that, one would have to get back to the desktop Zotero version and assign the articles of interest to such a collection, which is less than ideal.

Sure, one could already send the PDFs of interest to another application, but there are numerous issues associated with that workflow. I think an integrated star / add to favorites mechanism that is easy to use and get back to would be highly beneficial.

Even though, this may eventually be superseded by the addition of proper collection management, I think such a one-tap feature may remain useful even more advanced collection and tag management are present (it may also be beneficial for the desktop version of Zotero as large collections quickly get out of hand).

Ultimately, I guess it depends on the development effort required. My estimates are rather low:
- add a button / share list entry,
- create a dedicated collection if it doesn't already exist, 
- add the current item to that collection if it is not already in it
- update the data on the Zotero server

with some extras, such as:
- check if the current item is in that collection and display a corresponding marker
- disable / hide the button / share item if the item is already starred 

but I am not an expert and my limited experience with iOS development certainly renders my estimates rather naive.

**Comment by mronkko** [comment]
A favourites collection is an idea that should be considered. However, the diffference between this and full collection membership editing is only in the user interface code, and the degree of effort needed may be about the same. But this may be useful even when full collection membership editing is implemented.

Read-only support for tags is almost done now.

**Comment by mronkko** [comment]
One more thing, would you need this feature to sync with Zotero, or should the favourites list be stored only locally on ZotPad?

**Comment by philip-iii** [comment]
Yes, this would essentially be only a user interface "shortcut", but I am guessing it could also serve as a building block for full collection management and thus be made available in advance before the collection management is fully supported.

Regarding syncing, ideally it would sync with Zotero so that the favorites are available across devices, but a first iteration with local storage only will also be useful (not the least to test out and refine the idea).

**Comment by mronkko** [comment]
OK. Can you make a summary of this to UserVoice so that it is more easily discoverable by others that may be interested in this feature?

http://zotpad.uservoice.com

**Comment by philip-iii** [comment]
Posted on UserVoice as suggested: http://zotpad.uservoice.com/forums/172475-general/suggestions/3292192-add-support-for-starring-favorites

**Comment by mronkko** [comment]
Implemented
